### ISSUE TITLE
Add option to make paths case-insensitive

### ISSUE THREAD

**Issue by sergkr** [myquay/JsonPatch#10]
If you do something like this inside your startup Web API config to [convert serialized property names to camel case](http://odetocode.com/blogs/scott/archive/2013/03/25/asp-net-webapi-tip-3-camelcasing-json.aspx):

    // Convert JSON property names to camel case
    config.Formatters.JsonFormatter.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();

You won't be able to use camel case property names in your patch document (since the paths are case sensitive).  That means in order to be able to use this library, you either have to get rid of the camel casing in your API entirely (forcing the clients to use pascal case, which goes against the convention), or force the client to send paths with different casing than what they received (so as to match the original casing on the C# properties).  Neither of these options is very appealing...

Would it be possible to make case-sensitivity of paths configurable, or disable it entirely? I noticed there's a pull request for this (#7), but the author decided to close it...

**Comment by myquay** [comment]
Adding support for additional path name resolvers is a fantastic idea.

Right now it's just hard-coded, but it would be awesome to make it configurable and be able to specify a different resolver on configuration.

e.g. 

    config.Formatters.Add(new JsonPatchFormatter(new JsonPatchSettings
    {
        pathResolver = new CamelCasePropertyPathResolver()
    }));
 
I think it'd be preferable to keep it case sensitive by default because C# is, but it would be great to have it as an easy option to change on setup.  

Do you feel comfortable at taking a stab at it? I'm happy to help out if you have any questions or run into any problems :)

**Comment by sergkr** [comment]
Sure, I'll take a look.

**Comment by donaldgray** [comment]
I'm going to try and get this done this week.

I think it makes sense to be able to specify which resolver to use using something like the JsonPathSettings example in @myquay suggestion above.  I'm thinking the following 3 would do for now, what do you think?
- CamelCasePropertyPathResolver (foo -> Foo, case sensitive)
- MaintainCasePropertyPathResolver (Foo -> Foo, case sensitive)
- CaseInsensitivePropertyPathResolver (case insensitive)

**Comment by sergkr** [comment]
That sounds good to me... the only minor gripe is maybe rename `MaintainCasePropertyPathResolver ` to `ExactCasePropertyPathResolver`?

**Comment by donaldgray** [comment]
Yeah, makes sense - ExactCase is better than MaintainCase.

**Comment by myquay** [comment]
Hi @donaldgray how did you get on with this? Looking at finalising the feature set for the next version of JsonPatch and this is some functionality that I want to include.

**Comment by donaldgray** [comment]
Hi @myquay  - not as far as I wanted.

Apologies for this as it's been at the top of my todo list for an overly long time. I've been really snowed under but I do need this functionality for some upcoming changes I'm making to current project.

I can drop in the 'case insensitive' changes I made a while back if you need something in the meantime and I'll work on this over the next week or so?
