### ISSUE TITLE
Support MVC 6

### ISSUE THREAD

**Issue by lukas-shawford** [myquay/JsonPatch#16]
See here: https://github.com/aspnet/Mvc/issues/650#issuecomment-73432527

> From the looks of it, you will have to create an InputFormatter and OutputFormatter, the rest doesn't seem to require changes. You can look at [StringOutputFormatter](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/StringOutputFormatter.cs) or [StreamOutputFormatter](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Formatters/StreamOutputFormatter.cs) as an example for a greedy formatter. There is no sample for an input counterpart, but its rather simple.

Also, as explained [here](http://www.strathweb.com/2014/11/formatters-asp-net-mvc-6/):

> While in ASP.NET Web API formatters were bi-directional – single object handling both input and output, in MVC 6 the concept of formatters became uni-directional.

So, the current [JsonPatchFormatter](https://github.com/myquay/JsonPatch/blob/master/src/JsonPatch/Formatting/JsonPatchFormatter.cs) should be made into an input formatter. I'm not sure yet if we actually need an output formatter or not - there's nothing special about the response (the spec doesn't say anything about it).  Technically, it's actually up to the library user to send the response in their Patch handler method (our work ends at the call to `ApplyUpdatesTo`).  They can just send a 200 OK with the full entity in the response (serialized as JSON or XML, or whatever other serializer was chosen by content negotation), or maybe a 204 No Content.

**Comment by RehanSaeed** [comment]
ASP.NET 5 already supports it it seems https://github.com/aspnet/Mvc/pull/2201.
