### ISSUE TITLE
Release JsonPatch 2.0.0

### ISSUE THREAD

**Issue by realistschuckle** [myquay/JsonPatch#17]
Now that "add" works according to spec, can you release JsonPatch 2.0.0? If you find that you don't have time to do release management, I will happily help you. I plan on bringing JsonPatch into my current project and have a vested interest in the project's maturation.

**Comment by myquay** [comment]
Hey! Thanks for the offer :) 

Want to bring a few more features in before I do a proper release, I have uploaded the current version as a pre-release. You can get it using the following command:

    Install-Package JsonPatch -Pre

Cheers!
