### ISSUE TITLE
Respect JsonFormatter settings and [DataMember] attributes.

### ISSUE THREAD

**Issue by akozmic** [myquay/JsonPatch#19]
It looks like the paths on the operations directly correspond to C# expressions.   So  /User/FirstName refers to  User.FirstName.  There's another issue that suggests to make the paths case-insensitive, but to me that's only a part of the problem.

For instance, you might have a property called 'UserId' in your code, but mark it with [DataMember(Name="id")]   so  when UserId goes over the wire it shows up to the consumer as  { "id" : 12 }   not {  "UserId": 12 }.    Then if they were to try to PATCH that back in, the consumer would assume the model structure required "id"  not "UserId."

Another issue is with Json Serializer settings.   If you set your contract resolver to use CamelCasePropertyNamesContractResolver,  even "UserId" will serialize and deserialize as "userId"  which won't match up exactly with the C# expression.

Anyways, just wanted to bring these scencarios to your attention.

**Comment by myquay** [comment]
Thanks for the input and pull request - the datamember name is a great addition as generally we don't want the implementation details of the actual C# class to leak out to the API. Will review the referenced pull request shortly. Cheers.
