### ISSUE TITLE
Support for IDictionary

### ISSUE THREAD

**Issue by zihotki** [myquay/JsonPatch#23]
Currently IDictionary collections are not supported but dictionaries may be very useful for some scenarios to store key-value data. It should work in similar way as IEnumerable collections with some minor differences:

```
[
   { "op": "add", "path": "/Metadata/FooKey1", "value": "Bar" },  
   { "op": "replace", "path": "/Metadata/FooKey2", "value": "Bar" }, 
   { "op": "remove", "path": "/Metadata/FooKey3" }
]
```

The minor differences are:
- If there is already a key 'FooKey1' in metadata then it should throw an exception. 
- If there is no key 'FooKey2' then it should add a new item.
- If there is no key 'FooKey3' then it should not throw an exception.

The differences are caused by default behavior of Dictionary and probably it's better to keep them as is.

**Comment by zihotki** [comment]
FYI: I've already implemented the change for my personal project and will create a pull request soon if it makes sense for the project.

**Comment by myquay** [comment]
One part of me says leaky abstraction, the other part says it's good to enforce using the correct underlying datatypes in our models.

Right now I think it makes sense for the project, I'd appreciate a pull request so I can review.

**Comment by zihotki** [comment]
Yes, I agree that it may raise some concerns, but as practice shows very often you need to have some sort metadata for objects. And the natural and, IMO, best way to represent it in DTO models is to use dictionary.

**Comment by myquay** [comment]
Thanks for the PR - now supported, thanks.

**Comment by emilol** [comment]
I've installed the package from nuget and I'm not seeing the changes. The decompiled the source for 1.0.2 doesn't seem to show them. If I'm reading my timezones right it looks like the latest publish was shortly before this merge.

If this is now supported can it please be published to nuget? 🙂
