### ISSUE TITLE
Update NuGet package version

### ISSUE THREAD

**Issue by madmox** [myquay/JsonPatch#24]
We were desperatly looking for a JSON Patch library handling the `JsonProperty` attribute and it looks like this one does that. The issue is that the NuGet package (even the prerelease one) is very old and does not support this functionality...

Is it possible to publish a new version of the package on NuGet with the latest changes, or is it still under testing?

**Comment by zihotki** [comment]
I would say that it's stable enough and can be published at any time. I've built an internal package using the sources and already using it for a long time, if that works for you you can do that too, at least in meanwhile. Also I would like to mention that there is one change pending (I forgot about it under workload at work) about IDictionary support, I'll send a pull request ASAP this evening.

**Comment by madmox** [comment]
I think we will fork your project for now and host an updated version of the package on our own internal NuGet server. We'll switch back to yours when it's published!

**Comment by myquay** [comment]
The package has been updated on NuGet. The release includes support for handling the `[JsonProperty]` attribute.
