### ISSUE TITLE
NuSpec file has different dependency than csproj

### ISSUE THREAD

**Issue by smarts** [myquay/JsonPatch#28]
The Nuspec file specifies a dependency version of Microsoft.AspNet.WebApi.Client 5.2.0 and the csproj has 5.2.3
If you create a project from scratch, add Microsoft.AspNet.WebApi.Client 5.2.0 and then add JsonPatch it will fail to compile saying that JsonPatch references 5.2.3 but the project uses 5.2.0

I'm guessing it has to do with the reference in the csproj being a fully qualified assembly reference (with the version, public key token, etc.) instead of just having the assembly name.

**Comment by myquay** [comment]
The dependencies have been corrected for the latest NuGet build.
