### ISSUE TITLE
Support Dictionaries

### ISSUE THREAD

**Issue by johnmcase** [myquay/JsonPatch#29]
It is not uncommon for JSON objects and properties to be represented in POCOs as Dictionaries, be it Dictionary<string, int> or Dictionary<string, string> or whatever.

Json.Net seamlessly handles parsing JSON to/from dictionaries without any special setup.

JsonPatch however does not support patching POCOs with Dictionaries.

Suppose I have a JSON document:

```
{
    'dynamicProperties': {
        'field1': 'foo',
        'field2': 'bar'
    }
}
```

Mapped to the the POCO:

```
class MyClass
{
    IDictionary<string, string> dynamicProperties {get; set;}
}
```

And I send the following patch:

```
[
    {"op": "replace", "path": "/dyncamicProperties/field1", "value": "something else"}
]
```

```
The path \"/dyncamicProperties/field1\" is not valid: There is no property named \"field1\" on type Dictionary
```

**Comment by johnmcase** [comment]
OK, after looking into this a little more I'm confused.  It looks like you already added support for dictionaries with pull request #25.  Based on timing it looks like this should be included in the 1.0.2 release on NuGet but I don't see the new DictionaryPathResolver class that was added as part of that PR.

Did the publish to NuGet not work properly?  Or am I missing something obvious?

**Comment by zihotki** [comment]
I've checked the nuget version and it's indeed missing, in our company we didn't switch back from private version to the public nuget so I didn't notice the issue.
@myquay can you please re-publish it?

**Comment by PavelPikat** [comment]
Hi. Can you please republish NuGet package?
