### ISSUE TITLE
DTO example not working?

### ISSUE THREAD

**Issue by snebjorn** [myquay/JsonPatch#30]
Hi I'm testing out this library, and it looks really cool :)

However I'm having some issues getting the provided example to work.

```C#
public void Patch(Guid id, JsonPatchDocument<SomeDto> patchData)
{
    //Remember to do some validation and all that fun stuff
    var objectToUpdate = repository.GetById(id);
    patchData.ApplyUpdatesTo(objectToUpdate);
    repository.Save(objectToUpdate);
}
```

`JsonPatchDocument<SomeDto> patchData` implies that it works with DTOs.
But the `patchData.ApplyUpdatesTo()` takes the same type as `patchData` which is the DTO.

To my knowledge you don't use DTOs in your repository but domain models. So there's a type mismatch.

Putting some types on the example make the issue obvious :)
```C#
public void Patch(Guid id, JsonPatchDocument<FooDto> patchData)
{
    //Remember to do some validation and all that fun stuff
    Foo objectToUpdate = repository.GetById(id);
    patchData.ApplyUpdatesTo(objectToUpdate); // <-- fails: expects a FooDto but was Foo
    repository.Save(objectToUpdate);
}
```

Am I use it wrong? Or does JsonPatch not support DTOs in this way?

**Comment by mindingdata** [comment]
You are write in two ways. 

- You should try and use a domain object/viewmodel/DTO when passing data out and not rely on your data models. 
- JsonPatch doesn't allow patching across different classes. 

What you are probably looking for is Automapper (http://automapper.org/). Then you "map" objects between a DTO and your data model. Your code would look something like this. 

```
public void Patch(Guid id, JsonPatchDocument<FooDto> patchData)
{
    //Remember to do some validation and all that fun stuff
    Foo objectToUpdate = repository.GetById(id);
    FooDto existingObject = _mapper.Map(objectToUpdate); // Map our data model to our DTO
    patchData.ApplyUpdatesTo(existingObject); // <-- Apply patches to the DTO
    _mapper.Map(existingObject, objectToUpdate); // Map our DTO back to our existing object. 
    repository.Save(objectToUpdate); // Save. 
}
```

**Comment by snebjorn** [comment]
Thanks for the answer :)
That solution makes sense 👍

**Comment by myquay** [comment]
Thanks @mindingdata
