### ISSUE TITLE
Support Swagger/Swashbuckle

### ISSUE THREAD

**Issue by stienessen** [myquay/JsonPatch#33]
When adding a patch operation to a service that has swashbuckle (swagger) setup on it, the example service along with the swagger json definition for the service provides the incorrect definition of what a request should look like... i.e.

{
  "operations": [
    {
      "operation": "add",
      "fromPath": "string",
      "parsedFromPath": [
        {
          "name": "string",
          "componentType": "string",
          "isCollection": true
        }
      ],
      "path": "string",
      "parsedPath": [
        {
          "name": "string",
          "componentType": "string",
          "isCollection": true
        }
      ],
      "value": {}
    }
  ],
  "hasOperations": true
}

**Comment by imukai** [comment]
If this is still an issue for you, this article relates to a different implementation, but the same symptoms you describe, and how you might fix it.  That fix may be slightly different for this particular library.  I've been trying to find a library that wasn't dead in the water.  Anyway.. their fix:

[http://www.michaelware.net/2017/06/17/Using-Marvin-JsonPatch-and-Swashbuckle-to-Generate-Swagger-Documents/](http://www.michaelware.net/2017/06/17/Using-Marvin-JsonPatch-and-Swashbuckle-to-Generate-Swagger-Documents/)
