### ISSUE TITLE
Enum Parsing Case Sensitivity

### ISSUE THREAD

**Issue by broderickt2** [myquay/JsonPatch#52]
For my specific scenario, I am trying to upgrade to the latest version. I am coming from version 1.0.2 which is a bit old to be honest. In my testing, I noticed that is now seems enum case sensitivity is now being enforced. For example, here is a sample class and setup:

```
//Class setup
public class EnumEntity
{
	public SampleEnum Foo { get; set; }
}

//Enum setup
public enum SampleEnum
{
	FirstEnum,
	SecondEnum,
	ThirdEnum,
}


//Code to patch the enum
var entity = new EnumEntity
{
	Foo = SampleEnum.FirstEnum
};

var newEnumValue = "secondenum";

patchDocument.Replace(nameof(EnumEntity.Foo), newEnumValue);
patchDocument.ApplyUpdatesTo(entity);
```

So "secondenum" won't work (it throws an exception) but "SecondEnum" does which is the normal/expected use case. I checked the release notes and commits and cannot find much about this. I think the expectation is that case sensitivity should not matter for enums.

@myquay I know what specific parts of the code need tweaked to change this as shown in my screenshot below:
![image](https://github.com/myquay/JsonPatch/assets/93213727/7f93b426-2c30-42ce-8eef-e078cd5145bf)

Do you have any concerns if I make this tweak, add some unit tests, and open a pull request?

**Comment by broderickt2** [comment]
@myquay I went ahead and opened a [pull request here](https://github.com/myquay/JsonPatch/pull/53) to tweak this. Let me know if you want anything changed.

**Comment by myquay** [comment]
Hi @broderickt2 - no concerns, that PR looks good, thanks for submitting! Have merged it and the changes will be in the next release.
