### ISSUE TITLE
IDictionary properties not handled as dictionaries

### ISSUE THREAD

**Issue by idrm** [myquay/JsonPatch#55]
Declaring a property as `IDictionary<K,V>` instead of `Dictionary<K,V>` prevents JsonPatch from treating it as a dictionary.

You can see that behavior by changing the type of `Foo` in `DictionaryEntity.cs` to `IDictionary<TKey, string>` and then running the tests.

A fix for this is changing the logic of `IsDictionary` in `PathComponent.cs` to the following:

```cs
return typeof (IDictionary).IsAssignableFrom(ComponentType) ||
    typeof(IDictionary<,>).IsAssignableFrom(ComponentType) || (
        ComponentType.IsGenericType && (
        typeof(IDictionary).IsAssignableFrom(ComponentType.GetGenericTypeDefinition()) ||
        typeof(IDictionary<,>).IsAssignableFrom(ComponentType.GetGenericTypeDefinition())
    ));
```

P.S. Though the above passes all tests, there may be a more optimal way to implement the check.

**Comment by myquay** [comment]
Hi @idrm, thanks for reporting & submitting a fix for that issue.
