### ISSUE TITLE
GetProperty is internal so seems like no way to create custom resolver

### ISSUE THREAD

**Issue by chengbo** [myquay/JsonPatch#58]
Hello thanks for creating this amazing library.

I'm trying to integrate it into one of my projects, the problem is our models are using the `JsonPropertyName` attribute so I need to implement my own Resolver to handle it, just like [AttributePropertyPathResolver](https://github.com/myquay/JsonPatch/blob/master/src/JsonPatch.Common/Paths/Resolvers/AttributePropertyPathResolver.cs).

But the [GetProperty](https://github.com/myquay/JsonPatch/blob/master/src/JsonPatch.Common/Paths/Resolvers/BaseResolver.cs#L27) method is marked as `internal` so I don't know how to implement it, any suggestion?

**Comment by myquay** [comment]
Yep, that's a good use case, I'll mark that as public to allow the `BaseResolver` to be extended in that way.
